# Site settings

title: Project Pages
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/project-pages"
url: "http://matin-hub.github.io"
github_username:  matin-hub
project_repository: project-pages
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Prose Settings
prose:
  rooturl: '_posts'
  siteurl: 'http://matin-hub.github.io/project-pages/'
 # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'img'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "select"
          label: "Choose Layout"
          placeholder: "Layouts"
          options:
            - name: "Post"
              value: "post"
            - name: "Slide"
              value: "slide"
            - name: "Projector"
              value: "projector"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Choose Layout"
          value: ""
      - name: "horizontal"
        field:
          element: "hidden"
          value: </section></section><section markdown="1" data-background="http://matin-hub.github.io/project-pages/img/slidebackground.png"><section markdown="1">

